name: Build on macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
#    container:
#      image: cimg/python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker
        uses: docker/setup-docker@v1
        with:
          version: 20.10.7
      - name: Build the Docker image
        run: docker build . -t your-docker-image